CREATE OR REPLACE PROCEDURE FIND_EMPLOYEE_BY_ID (
    ID_EMPLOYEE IN NUMBER,
    RESULTSET OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTSET FOR
    SELECT
        ID
        , E.NOMBRE AS NAME
        , E.FECHANACI AS BIRTHDATE
        , E.SALARIO AS SALARY
        , E.DIASTRABAJADOS AS WORKINGDAY
    FROM EMPLEADOS E
        WHERE ID = ID_EMPLOYEE;
END FIND_EMPLOYEE_BY_ID;